export const templatesList = [
  {
    id: "Template01",
    name: "Professional Classic",
    key: "Richard Sanchez",
    image: "/template/template01n.png",
    category: "modern",
  },
  {
    id: "Template47",
    name: "Classic",
    key: "Richard",
    image: "/template/template47.png",
    category: "modern",
  },
  {
    id: "Template30",
    name: "Professional Resume",
    key: "John Doe",
    image: "/template/template30.png",
    category: "modern",
  },
  {
    id: "Template31",
    name: "Modern Professional",
    key: "Your Name",
    image: "/template/template30.png", // Placeholder image
    category: "modern",
  },
  {
    id: "Template32",
    name: "Executive Resume",
    key: "Rahul Menon",
    image: "/template/Template32.png",
    category: "simple",
  },
  {
    id: "Template33",
    name: "Olivia Modern",
    key: "Olivia Wilson",
    image: "/template/template33.png",
    category: "proffessional",
  },
  {
    id: "Template34",
    name: "Modern Creative",
    key: "Emily Davis",
    image: "/template/template34.jpg",
    category: "creative",
  },
  {
    id: "Template35",
    name: "Elegant Layout",
    key: "David Wilson",
    image: "/template/template35.jpg",
    category: "proffessional",
  },
  {
    id: "Template36",
    name: "Modern Creative",
    key: "Aaradhya Nair",
    image: "/template/template36.png",
    category: "creative",
  },
  {
    id: "Template37",
    name: "Stylish Resume",
    key: "Sophia Lee",
    image: "/template/template37.jpg",
    category: "modern",
  },
  {
    id: "Template38",
    name: "Modern Creative",
    key: "Emily Davis",
    image: "/template/template38.png",
    category: "creative",
  },
  {
    id: "Template39",
    name: "Clean Creative",
    key: "Emily Davis",
    image: "/template/LEONARDOX NERO-1.png",
    category: "professional",
  },
  {
    id: "Template40",
    name: "Modern Creative",
    key: "David Wilson",
    image: "/template/template40.jpg",
    category: "modern",
  },
  {
    id: "Template41",
    name: "Stylish Classic",
    key: "Emily Davis",
    image: "/template/ARTHAVION.png",
    category: "modern",
  },
  {
    id: "Template42",
    name: "Creative Classic",
    key: "Emily Davis",
    image: "/template/TITANUS ZORIN.png",
    category: "creative",
  },
  {
    id: "Template43",
    name: "Stylish Layout",
    key: "Emily Davis",
    image: "/template/VORTEXION ZAYNIX.png",
    category: "modern",
  },
  {
    id: "Template44",
    name: "proffessional",
    key: "Emily Davis",
    image: "/template/ASTROLON.png",
    category: "modern",
  },
  {
    id: "Template45",
    name: "Modern Creative",
    key: "Emily Davis",
    image: "/template/RAVENOR.png",
    category: "modern",
  },
  {
    id: "Template46",
    name: "Modern Creative",
    key: "Emily Davis",
    image: "/template/AUGUSTUS AXEL.png",
    category: "modern",
  },
];