// components/templates/index.js

import Template01 from "./Template01";
import Template30 from "./Template30";
import Template31 from "./Template31";
import Template32 from "./Template32";
import Template34 from "./Template34";
import Template35 from "./Template35";
import Template33 from "./Template33";
import Template36 from "./Template36";

import Template37 from "./Template37";
import Template38 from "./Template38";
import Template39 from "./Template39";
import Template40 from "./Template40";
import Template41 from "./Template41";
import Template42 from "./Template42";
import Template43 from "./Template43";
import Template44 from "./Template44";
import Template45 from "./Template45";
import Template46 from "./Template46";
import Template47 from "./Template47";

export const templates = {
  template01: Template01,
  template30: Template30,
  template31: Template31,
  template32: Template32,
  template34: Template34,
  template35: Template35,
  template36: Template36,
  template37: Template37,
  template33: Template33,
  template38: Template38,
  template39: Template39,
  template40: Template40,
  template41: Template41,

  template42: Template42,
  template43: Template43,
  template44: Template44,
  template45: Template45,
  template46: Template46,
  template47: Template47,



};

export const templateInputs = {
  template01: {
    name: true,
    title: true,
    about: true,
    profileImage: false,
    skills: true,
    phone: true,
    email: true,
    address: true,
    languages: true,
    Summary: true,
    experiences: true,
    education: true,
    certificates: false,
    project: true,
    socialLinks: true,
    references: true,
    awards:true,
    
  },
 


  template34: {
    name: true,
    title: true,
    Summary: true,
    experiences: true,
    education: true,
    about: true,
    profileImage: true,
    skills: true,
    socialLinks: true, 
    certificates: true, 
    maritalStatus: true, 
  },

  template35: {
    name: true,
    title: true,
    profileImage: false,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
  },

  template30: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    skills: true,
    languages: true,
    Summary: true,
    experiences: true,
    education: true,
    certificates: true,
    project: true,
    socialLinks:true
    

  },

  template31: {
    name: true,
    title: true,
    about: true,
    profileImage: true,
    experience: true,
    education: true,
    skills: true,
  },

  template32: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    languages: true,
    Summary: true,
    experiences: true,
    education: true,
    certificates: true,
  },
  template33: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    languages: true,
    Summary: true,
    experiences: true,
    education: true,
    certificates: true,
    references: true,
    awards:true, 
  },

  template36: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    languages: true,
    Summary: true,
    experiences: true,
    education: true,
    certificates: true,
  },


  template36: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    skills: true,
    languages: true,
    Summary: true,
    experiences: true,
    education: true,
    certificates: true,
  },


  template37: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
  },
  template38: {
    name: true,
    title: true,
    profileImage: false,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
    awards:true, 
  },
  template39: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
    awards:true, 
  },
  template40: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
  },

  template41: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
   references: true,
    awards:true, 
  },
  template42: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
    awards:true, 
  },
  template43: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
   references: true,
    awards:true, 
  },

  template44: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
    awards:true, 
  },
  template45: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
    awards:true, 
  },
  template46: {
    name: true,
    title: true,
    profileImage: true,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    education: true,
    skills: true,
    languages: true,
    certificates: true,
    references: true,
    awards:true, 
  },
  template47: {
    name: true,
    title: true,
    profileImage: false,
    phone: true,
    email: true,
    address: true,
    summary: true,
    experiences: true,
    project: true,
    education: true,
    skills: true,
    languages: false,
    certificates: false,
    references: false,
  },
};
